import Data.List
import Control.Exception

main :: IO ()
main = do
    n <- readLn :: IO Int
    
    error "a"

